name: CI
on: [push]
jobs:
  build:
    name: Build and test on Node ${{ matrix.node }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['14.x', '16.x', '18.x']

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Check Formatting
        run: npm run prettier -- --check

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test:coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
